// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/user": {
            "post": {
                "description": "创建新用户。用户名和昵称长度 2-32，密码长度 8-20，用户名必须唯一。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "创建用户",
                "parameters": [
                    {
                        "description": "创建用户请求体",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.CommonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.UserResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.CreateUserRequest": {
            "type": "object",
            "required": [
                "nickname",
                "password",
                "username"
            ],
            "properties": {
                "nickname": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "model.UserResponse": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "credit": {
                    "type": "integer"
                },
                "gender": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "last_login_at": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                },
                "qq": {
                    "type": "string"
                },
                "realname": {
                    "type": "string"
                },
                "role": {
                    "type": "integer"
                },
                "status": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "response.Code": {
            "type": "integer",
            "enum": [
                0,
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                9,
                10001,
                10002,
                10003,
                10004,
                10005,
                10006,
                10007,
                10008,
                10009,
                10010,
                20001,
                20002,
                20003,
                20004,
                20005,
                20006,
                20007,
                20008,
                20009,
                20010,
                20011,
                20012,
                30001,
                30002,
                30003,
                30004,
                30005,
                30006,
                30007,
                30008,
                40001,
                40002,
                40003,
                40004,
                40005,
                40010,
                40011,
                50001,
                50002,
                50003,
                50004,
                50005,
                60001,
                60002,
                60003,
                70001,
                70002,
                70003,
                70004,
                80001,
                80002,
                80003,
                80004,
                90001,
                90002,
                90003
            ],
            "x-enum-varnames": [
                "CodeSuccess",
                "CodeParamError",
                "CodeUnauthorized",
                "CodeForbidden",
                "CodeNotFound",
                "CodeServerError",
                "CodeDatabaseError",
                "CodeTooManyRequests",
                "CodeOperationFailed",
                "CodeUnknownError",
                "CodeUserNotFound",
                "CodeUsernameOccupied",
                "CodePasswordWrong",
                "CodeTokenExpired",
                "CodeUserDisabled",
                "CodeOldPasswordWrong",
                "CodeEmailOccupied",
                "CodePhoneOccupied",
                "CodeFormInvalid",
                "CodeUserNotActive",
                "CodeItemNotFound",
                "CodeItemClosed",
                "CodeItemAlreadyClaimed",
                "CodeItemPendingAudit",
                "CodeItemNoPermission",
                "CodeItemTypeInvalid",
                "CodeItemCreditNegative",
                "CodeItemTimeEmpty",
                "CodeItemTitleEmpty",
                "CodeItemLocationInvalid",
                "CodeItemAlreadyPublished",
                "CodeItemCannotClaimSelf",
                "CodeClaimNotFound",
                "CodeClaimAlreadyExists",
                "CodeClaimAlreadyHandled",
                "CodeClaimCancelled",
                "CodeClaimNoPermission",
                "CodeClaimSelfItem",
                "CodeClaimDescriptionTooLong",
                "CodeClaimDuplicate",
                "CodeTagNotFound",
                "CodeTagDuplicate",
                "CodeTagDisabled",
                "CodeTagNameInvalid",
                "CodeTagInUse",
                "CodeItemTagExists",
                "CodeItemTagNotFound",
                "CodeCreditInsufficient",
                "CodeCreditLogNotFound",
                "CodeCreditTypeInvalid",
                "CodeCreditAmountInvalid",
                "CodeCreditAlreadyRewarded",
                "CodeNotificationNotFound",
                "CodeNotificationNoPermission",
                "CodeNotificationAlreadyRead",
                "CodeReportNotFound",
                "CodeReportDuplicate",
                "CodeReportSelfContent",
                "CodeReportAlreadyHandled",
                "CodeLocationNotFound",
                "CodeLocationDuplicate",
                "CodeLocationDisabled",
                "CodeLocationInUse",
                "CodeAnnouncementNotFound",
                "CodeAnnouncementNoPermission",
                "CodeAnnouncementInvalid"
            ]
        },
        "response.CommonResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/response.Code"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
