definitions:
  model.AddUserCreditRequest:
    properties:
      credit:
        type: integer
      description:
        type: string
      id:
        type: integer
      operator_id:
        type: integer
      type:
        type: integer
    required:
    - credit
    - id
    - operator_id
    - type
    type: object
  model.ChangeUserRoleRequest:
    properties:
      id:
        type: integer
      role:
        type: integer
    required:
    - id
    - role
    type: object
  model.ChangeUserStatusRequest:
    properties:
      id:
        type: integer
      status:
        type: integer
    required:
    - id
    - status
    type: object
  model.CreateUserRequest:
    properties:
      nickname:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - nickname
    - password
    - username
    type: object
  model.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  model.LogoutRequest:
    properties:
      logout_all:
        type: integer
    required:
    - logout_all
    type: object
  model.QQBindRequest:
    properties:
      code:
        type: integer
      qq:
        type: integer
    required:
    - code
    - qq
    type: object
  model.QQGetCodeRequest:
    properties:
      qq:
        type: integer
    required:
    - qq
    type: object
  model.UpdateUserRequest:
    properties:
      avatar:
        type: string
      gender:
        type: integer
      nickname:
        type: string
      realname:
        type: string
    type: object
  model.UserResponse:
    properties:
      avatar:
        type: string
      created_at:
        type: string
      credit:
        type: integer
      gender:
        type: integer
      id:
        type: integer
      last_login_at:
        type: string
      nickname:
        type: string
      qq:
        type: string
      realname:
        type: string
      role:
        type: integer
      status:
        type: integer
      updated_at:
        type: string
      username:
        type: string
    type: object
  response.Code:
    enum:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 10001
    - 10002
    - 10003
    - 10004
    - 10005
    - 10006
    - 10007
    - 10008
    - 10009
    - 10010
    - 10011
    - 10012
    - 10013
    - 10014
    - -1
    type: integer
    x-enum-varnames:
    - CodeSuccess
    - CodeParamError
    - CodeUnauthorized
    - CodeForbidden
    - CodeNotFound
    - CodeServerError
    - CodeDatabaseError
    - CodeUnknownError
    - CodeChenSongError
    - CodeUserOrPasswordError
    - CodeUsernameOccupied
    - CodeFormInvalid
    - CodeInvalidSigningMethod
    - CodeTokenBanned
    - CodeUserNotFoundOrBanned
    - CodeQQSessionAlreadyExists
    - CodeQQCodeError
    - CodeQQUserNotInGroup
    - CodeQQNumberError
    - CodeQQTooManyRequests
    - CodeQQSessionNotExist
    - CodeQQAlreadyRegistered
    - CodeCreditNotEnough
    - CodeTest
  response.CommonResponse:
    properties:
      code:
        $ref: '#/definitions/response.Code'
      data: {}
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/user/admin-add-credit:
    post:
      consumes:
      - application/json
      description: Role为2的用户改变任意用户积分，可选为SET或ADD (is_delta)
      parameters:
      - description: 变更用户角色请求
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.AddUserCreditRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.CommonResponse'
      summary: 系统管理员改变用户积分
      tags:
      - user
  /api/v1/user/admin-change-role:
    post:
      consumes:
      - application/json
      description: Role为2的用户改变任意用户Role为0/1/2
      parameters:
      - description: 变更用户角色请求
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.ChangeUserRoleRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.CommonResponse'
      summary: 系统管理员改变用户角色
      tags:
      - user
  /api/v1/user/admin-change-status:
    post:
      consumes:
      - application/json
      description: Role为2的用户改变任意用户Status为0(禁用)/1(正常)
      parameters:
      - description: 变更用户角色请求
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.ChangeUserStatusRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.CommonResponse'
      summary: 系统管理员改变用户状态(禁用)
      tags:
      - user
  /api/v1/user/create:
    post:
      consumes:
      - application/json
      description: 创建新用户。用户名和昵称长度 2-32，密码长度 8-20，用户名必须唯一。
      parameters:
      - description: 创建用户请求体
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.CreateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.CommonResponse'
            - properties:
                data:
                  $ref: '#/definitions/model.UserResponse'
              type: object
      summary: 创建用户
      tags:
      - user
  /api/v1/user/login:
    post:
      consumes:
      - application/json
      description: '用户使用用户名和密码登录，验证通过后返回用户信息并在响应体 Header 设置 Authorization : Token'
      parameters:
      - description: 用户登录请求体
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.CommonResponse'
            - properties:
                data:
                  $ref: '#/definitions/model.UserResponse'
              type: object
      summary: 用户登录
      tags:
      - user
  /api/v1/user/logout:
    post:
      consumes:
      - application/json
      description: 选择全部登出或仅当前会话登出
      parameters:
      - description: 用户登出请求体
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.LogoutRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.CommonResponse'
      summary: 用户登出
      tags:
      - user
  /api/v1/user/qq/bind:
    post:
      consumes:
      - application/json
      description: 用户在统一jti会话中验证验证码，最大次数不超过5次/3分钟 <br />接收json为number，但后端实际操作统一用string
      parameters:
      - description: 绑定QQ请求
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.QQBindRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.CommonResponse'
      summary: 用户通过验证码绑定qq
      tags:
      - user
  /api/v1/user/qq/get-code:
    post:
      consumes:
      - application/json
      description: 后端生成验证码并让陈松发送
      parameters:
      - description: 获取qq验证码请求
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.QQGetCodeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.CommonResponse'
      summary: 用户申请获取qq验证码
      tags:
      - user
  /api/v1/user/update:
    post:
      consumes:
      - application/json
      description: 用户更改昵称、真名、性别、头像
      parameters:
      - description: 用户登出请求体
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.UpdateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.CommonResponse'
      summary: 用户更改信息
      tags:
      - user
swagger: "2.0"
